/**
 * Created by Administrator on 2016/8/31.
 */
var jsonDate = [
    {
        model:"账户相关",
        rank:1,
        href:"account",
        children:[{
            childrenRank:1,
            name:"注册过的手机号还能再注册吗？",
            shortName:"",
            isShowIndex:false,
        },{
            childrenRank:2,
            name:"怎么修改我的昵称（账户名称）？",
            shortName:"昵称变更",
            isShowIndex:true,
        },{
            childrenRank:3,
            name:"我的账户疑似被盗了，怎么办？",
            shortName:"",
            isShowIndex:false,
        },{
            childrenRank:4,
            name:"我是否可以自行注销好闲置的账户？",
            shortName:"",
            isShowIndex:false,
        },{
            childrenRank:5,
            name:"账户无法登录的原因有哪些？",
            shortName:"",
            isShowIndex:false,
        },{
            childrenRank:6,
            name:"注册时必须要绑定个人手机号吗？",
            shortName:"",
            isShowIndex:false,
        },{
            childrenRank:7,
            name:"无法接收到短信验证码该怎么办？",
            shortName:"短信验证",
            isShowIndex:true,
        },{
            childrenRank:8,
            name:"怎么修改登陆密码？",
            shortName:"",
            isShowIndex:false,
        },{
            childrenRank:9,
            name:"使用第三方平台登陆的账户忘记密码了怎么办？",
            shortName:"",
            isShowIndex:false,
        },{
            childrenRank:10,
            name:"找回密码时，原注册或绑定的手机号不用了怎么办？",
            shortName:"解绑手机",
            isShowIndex:true,
        },{
            childrenRank:11,
            name:"换手机号后，原账户怎么修改旧的绑定手机？",
            shortName:"",
            isShowIndex:false,
        },{
            childrenRank:12,
            name:"有时候能接收到消息提醒，有时候则无法接收到，为什么？",
            shortName:"",
            isShowIndex:false,
        },{
            childrenRank:13,
            name:"发布商品时出现了闪退，怎么办？",
            shortName:"",
            isShowIndex:false,
        },{
            childrenRank:14,
            name:"App出现了异常闪退情况，怎么办？",
            shortName:"APP闪退",
            isShowIndex:true,
        }]
    },{
        model:"交易相关",
        rank:2,
        href:"deal",
        children:[
            {
                childrenRank:1,
                name:"平台交易需要收取手续费吗？",
                shortName:"提现费率",
                isShowIndex:true,
            },{
                childrenRank:2,
                name:"客服电话是多少?",
                shortName:"客服电话",
                isShowIndex:true,
            },{
                childrenRank:3,
                name:"交易流程?",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:4,
                name:"付款前，如何对订单进行修改？",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:5,
                name:"付款后，遇到发货问题，怎么办？",
                shortName:"退款去向",
                isShowIndex:true,
            },{
                childrenRank:6,
                name:"成功退款的资金，去哪里了？",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:7,
                name:"付款时多付或少付了金额，该怎么办？",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:8,
                name:"签收时，发现商品与原描述不符的，怎么办？",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:9,
                name:"确认收货，发现卖家虚假发货，该怎么办？",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:10,
                name:"什么情况下可以“确认收货？",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:11,
                name:"确认收货后，是否还能申请售后维权？",
                shortName:"售后维权",
                isShowIndex:true,
            },{
                childrenRank:12,
                name:"为什么购买前无法私信对方了？",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:13,
                name:"卖家不发货，怎么办？",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:14,
                name:"联系不上卖家了，怎么办？",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:15,
                name:"怎么搜索商品或用户？",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:16,
                name:"我要修改收件地址/新增收货地址，在哪里设置？",
                shortName:"",
                isShowIndex:false,
            },{
                childrenRank:17,
                name:"平台支持哪些付款方式？",
                shortName:"",
                isShowIndex:false,
            }
        ]
    }
];